### ISSUE TITLE
Vanilla shelf quality visible

### ISSUE THREAD

**Issue by WorstGirl** [lilwhitemouse/RimWorld-LWM.DeepStorage#132]
Vanilla shelves always show their quality since the rebalancing update. Only happens with the mod installed.

![5vmtg1](https://user-images.githubusercontent.com/37132854/203905036-4a5154b3-9dfe-4a9e-be65-81d2ab46ec83.jpg)

**Comment by lilwhitemouse** [comment]
I believe this is fixed in the latest version

**Comment by WorstGirl** [comment]
Confirmed fixed in the latest update. Thanks!
