### ISSUE TITLE
Can't Right click at all

### ISSUE THREAD

**Issue by 893203** [lilwhitemouse/RimWorld-LWM.DeepStorage#139]
tried validating game files, didn't work. not entirely sure if this mod is causing it but might as well.

Here's the log:
https://gist.github.com/HugsLibRecordKeeper/e8d6d4b44cbce7068d35d12d93236529

**Comment by lilwhitemouse** [comment]
I'm not sure I see anything going on there :(
Deep storage barely touches anything right-click related, so it's very unlikely. You can make sure the mod setting for "deep storage right click logic" is turned off (and restart), but other than that....good luck?
