### ISSUE TITLE
Increase Weapons Locker mass and bulk capacities

### ISSUE THREAD

**Issue by sumghai** [lilwhitemouse/RimWorld-LWM.DeepStorage#14]
**Proposal:** Increase Weapons Locker mass capacity to **72** kg, and Combat Extended bulk capacity to **205**

**Rationale**:

I originally conceived each locker to store up to 4~5 vanilla assault rifles, based on this [image](https://user-images.githubusercontent.com/4993380/54060575-236bb400-4262-11e9-8cab-3e8a22737cc2.png). However, it turned out that not only was that particular locker not utilizing its capacity to 100%, but said locker is actually only around waist-to-chest high.

Since the Locker in-game is supposed to be as tall as structural walls, the real-life equivalents actually  [look more like this](https://user-images.githubusercontent.com/4993380/54060855-2f0baa80-4263-11e9-8f9b-2a8716739d48.jpg), which can hold at least 20 vanilla assault rifles.

Furthermore, the current CE patch specifies a bulk capacity value of 55, which is roughly equivalent to two CE backpacks. A locker is obviously much bigger than a backpack, and so its bulk value should be increased accordingly.

Below is a screenshot of the updated capacity calculations spreadsheet - these include considerations for mod assault rifles and pistols:

![calcs](https://user-images.githubusercontent.com/4993380/54061251-e5bc5a80-4264-11e9-938e-61cea0a31077.png)

**Comment by lilwhitemouse** [comment]
I finally have a chance to look at this!

Goodness, they pack a lot of rifles into there!  Thank you for the reference image.

I think it makes reasonable sense for CE to up the bulk, but for vanilla, the locker has to store more than just the rifle itself - it's also got to hold imaginary ammunition, cleaning equipment, etc.

I may set the mass to 12 assault rifles in Vanilla and greatly increase the stack count for things like knives, etc.  But for CE, I'll push your changes out shortly.

**Comment by lilwhitemouse** [comment]
I may also increase the cost to build - more mount points and options needing more metal, etc.  The picture

**Comment by lilwhitemouse** [comment]
I have updated CE as requested. I have updated vanilla at slightly lower capacities.  Thoughts?

**Comment by sumghai** [comment]
Yes, I like your rationale regarding lower max mass capacity in vanilla to account for imaginary ammo, cleaning and maintenance equipment (whereas a greater relative capacity is required for CE since CE introduces actual ammo resources).

I shall leave the rebalancing of building costs to your discretion :)

**Comment by lilwhitemouse** [comment]
Slightly further reduced capacity wooden cabinets: metal cabinets have mounting points that can be very precisely moved, whereas wooden cabinets are limited.

Commit:  8bb4f11fbebb8587240966090fd3355ade5d8fd3

Slightly increased cost of wooden cabinets (they're probably bigger than dressers).
Slightly decreased cost of metal cabinets, but reduced hitpoints as well.  This seems like a good incentive to incrase importance of machining.

Commit: b86ba61fa44be2294df20f61e81fc82b0b6b34a0

(Incidentally, added ability to hold artifacts; does NOT default to storing them - is a player feels it's not quite right, they don't have to use that ability)

**Comment by sumghai** [comment]
Sounds good.
