### ISSUE TITLE
ResourceCrates Only Store a Single Stack of Whatever Resources are Assigned

### ISSUE THREAD

**Issue by Nematocyst** [lilwhitemouse/RimWorld-LWM.DeepStorage#148]
1.4

For some reason, colonists can no longer store more than a single stack of say...wood on the Wood Storage Resource Crate.  It shows Wood x 75   30 Kg.  I remember being able to store up to 10 full stacks of wood but it doesn't work anymore.

**Comment by lilwhitemouse** [comment]
any error messages?

**Comment by lilwhitemouse** [comment]
(or full hugslib log?)

**Comment by Nematocyst** [comment]
Additionally, I got the Player.log.  Compressed because its 12 GB.

https://drive.google.com/file/d/1Hu6cMQ-ED5jRtELaIVbsIPbECiaYPqM_/view?usp=drive_link

**Comment by Nematocyst** [comment]
Hey, I think I might have cleared your mod as the culprit.  As with many woes, I think the problem was Combat Extended.  The game would throw a HUUGE list of errors at the beginning and after I removed it, bam, storage is working like it should again.
