### ISSUE TITLE
Combat Extended compatibility: Weapons not hidden inside Weapons Locker 

### ISSUE THREAD

**Issue by sumghai** [lilwhitemouse/RimWorld-LWM.DeepStorage#15]
At present, weapons stored inside the Weapons Locker are visually hidden from map view, as originally designed for gameplay aesthetics. The locker contents are, of course, listed in the accompanying Contents tab.

However, if a savegame is also running Combat Extended, then the stack of weapons in the Locker are shown back on the map.

Perhaps CE is doing something to the code that usually hides the weapons in non-CE games?

**Comment by sumghai** [comment]
I figured it out - the **Compatibility_CombatExended.xml** xpath patch file is missing the `<showContents>false</showContents>` node for the PatchOperationReplace operation modifying `<li Class='LWM.DeepStorage.Properties'>`.

Do you want me to make a pull request, or would you prefer to handle this on your end?

**Comment by lilwhitemouse** [comment]
I thought this was already set to false in vanilla?

I had, in fact, been thinking of turning it off (making it visible) if there is exactly one type of item in the locker, but I hadn't touched anything, I thought.

I'll take a look at it in the next few days.

--LWM

**Comment by lilwhitemouse** [comment]
Right.  The vanilla doesn't affect CE, because the entire <comp ...> is replaced.  *facepalm*  I will push that out to steam shortly.

**Comment by lilwhitemouse** [comment]
Fixed in latest version
