### ISSUE TITLE
d3d11: failed to create buffer

### ISSUE THREAD

**Issue by ufAdhBU** [lilwhitemouse/RimWorld-LWM.DeepStorage#155]
The display crashes and freezes completely but the game continues to run in background. I suspect DeepStorage. Any clue ?

[Player.log](https://github.com/lilwhitemouse/RimWorld-LWM.DeepStorage/files/15206036/Player.log)

Ln 715 :
> But...compds isn't null: CompDeepStorage(parent=Frame_LWM_Food_Basket340738 at=(129, 0, 118))
> d3d11: failed to create buffer (target 0x1 mode 0 size 480) [0x887A0005]
[...]
Ln 3561 :
> d3d11: failed to create buffer (target 0x2 mode 0 size 48) [0x887A0005]
> Setting up 6 worker threads for Enlighten.
>   Thread -> id: 3fc4 -> priority: 1 
>   Thread -> id: d1c -> priority: 1 
>   Thread -> id: 2930 -> priority: 1 
>   Thread -> id: 1fc0 -> priority: 1 
>   Thread -> id: 139c -> priority: 1 
>   Thread -> id: 214c -> priority: 1

**Comment by ufAdhBU** [comment]
It's a DirectX issue. Nothing to deal with DeepStorage.
Part of solution : https://ludeon.com/forums/index.php?topic=57115.msg496750#msg496750
My bad and thx for this mod!

**Comment by lilwhitemouse** [comment]
Amazing error and good solution hunting!
