### ISSUE TITLE
Finally put Weapon Cabinets into the game

### ISSUE THREAD

**Issue by lilwhitemouse** [lilwhitemouse/RimWorld-LWM.DeepStorage#20]

**Comment by lilwhitemouse** [comment]
Per @sumghai:

My rationale for metallic weapons lockers requiring machining research to unlock is that at the end of the day, this is a frontier RimWorld, where most things are relatively ramshackle.

So I reasoned that most players would build wooden weapons cabinets to fit the frontier theme, while the metal weapons locker would be reserved for those making very high tech industrial or spacer colonies.
But otherwise, both the cabinet and locker are intended to have exactly the same weapons capacity and dimensions. The difference between them is merely workmanship.

**Comment by lilwhitemouse** [comment]
I think I would put the amount storable in a wooden cabinet lower than in a metal one.

In the sample image you shared in https://github.com/lilwhitemouse/RimWorld-LWM.DeepStorage/issues/14, the weapons are really packed in there.  In a RimWorld setting, there would be movable thin metal hooks that a colonist could slot into the perfect position to store a large number of guns.
 
Wooden weapon cabinets - at least ones for guns in the US South - just cannot hold that many.  Slots for rifles have wooden board between them, which adds an extra 1/2"-1" (1-3cm) between rifles.  I don't think it would be a huge difference, but I think thin pressed metal is just going to be more flexible and thin.

**Comment by sumghai** [comment]
Okay, I agree with you there.

What I've done as part of commit 20c5949 in PR #18 is to readjust the the cabinet and locker capacities such that:
* Wooden Cabinets: 10 rifles in vanilla, 16 rifles in CE, storage time 100
* Metal Lockers: 14 rifles in vanilla, 20 rifles in CE, storage time 120

I also changed the description for the metal lockers to mention the difference in capacity compared with wooden cabinets.

**Comment by lilwhitemouse** [comment]
Heh.  I cannot make sense of this pull request any more...

**Comment by lilwhitemouse** [comment]
Okay, how does this look to you?

**Comment by sumghai** [comment]
Looks better.

FYI - it is easier to just accept a PR that is 90% right, and fix the remaining ten percent, than to delay a PR until it is 100% perfect.

**Comment by lilwhitemouse** [comment]
That's certainly ONE approach!
