### ISSUE TITLE
Show spoil timer in contents panel

### ISSUE THREAD

**Issue by jinlan** [lilwhitemouse/RimWorld-LWM.DeepStorage#24]
It's very hard to click every stack of fruit to check their spoil timer.

**Comment by lilwhitemouse** [comment]
If you can point me to the code (say a filename and function) that calculates that information for caravans or trading, I can almost certainly add it in.

**Comment by jinlan** [comment]
ThingWithComps.GetComp()
CompProperties_Rottable
daysToRotStart

**Comment by lilwhitemouse** [comment]
No worries re: pushing.

The "contents" tab needs some updating anyway - it will be easy enough to add this in when I do it!

**Comment by lilwhitemouse** [comment]
Take a look at latest build, see if it works well for you!
