### ISSUE TITLE
Strange behavior when pawn fully filled the storage.

### ISSUE THREAD

**Issue by jinlan** [lilwhitemouse/RimWorld-LWM.DeepStorage#27]
When multiple pawns trying to fill a storage, it will be quickly filled full. And when it's full and pawns' inventory still have remaining stuffs, pawns will "DANCE" near by permantly until downed.

Sometimes, I see pawn stand still, keeping "fill the storage" stance, FOR EVER, until downed. I'm not sure why.

Suggestion: "fill the storage" toil should be able detect "storage is full" event and stop the job accordingly.

My version is: 339ce17806a70c5c3fd7a220f1952e3ebbea0a06
--------------------------------------------------------------------------------------------------

I have about 1300 pemmican. I built a food basket to store it. One of my pawn started to haul all my 1300 pemmican and try to put it into that basket. When the basket is full, he just stand still. When I built another basket, he then go to haul the remaining pemmican to that new basket.

So I guess we should whether "preserve storage capacity" before haul or "check storage capacity" while filling the storage.

**Comment by lilwhitemouse** [comment]
If you have a save game where this is going on, that would be fantastically useful!

**Comment by lilwhitemouse** [comment]
Another important question: are you using Pick Up & Haul?

**Comment by lilwhitemouse** [comment]
(If so, is it still going on with the latest build of PU&H?)

**Comment by jinlan** [comment]
Yes, I'm using PU&H.
PU&H version: 649726c3319a5038c6f7d75f3f65beab301868df

save: https://raw.githubusercontent.com/jinlan/issue/master/1.rws

**Comment by jinlan** [comment]
Sorry for my English ability. It's not when food basket is full, pawn put down the pemmican, and when new basket is built, pawn re-haul the pemmican. It's when food basket is full, pawn stand still while holding all the remaining pemmican, when I built a new basket, he go to that new basket and put remaining pemmican to that new basket.

**Comment by lilwhitemouse** [comment]
Mehni pushed out a change to PickUp&Haul a few days ago: it might fix that problem.
I am pushing out a change today: IT might fix the problem.

Please make sure Steam updates the mods.

If you see this happen again, let me know, and we look into it!

(I hope these changes fix it)

**Comment by lilwhitemouse** [comment]
If this happens again, you may reopen the issue.
