### ISSUE TITLE
Deep Storage breaks a Toil if it is reused

### ISSUE THREAD

**Issue by lilwhitemouse** [lilwhitemouse/RimWorld-LWM.DeepStorage#31]
A series of problems with @Mehni's Pick Up & Haul (https://github.com/Mehni/PickUpAndHaul) have surfaced.  Reporting on Steam: (https://steamcommunity.com/app/294100/discussions/0/3570700856103815997/).

First part involved an update by LWM and a fix by Mehni.

Problems still happening: pawns stuck unable to unload inventory.
Debug trace shows no new jobs are assigned but pawn repeatedly hitting LWM's preInitAction in the PlaceHauledThingInCell toil.

Likely culprit: LWM eats the initAction and places it in final ticks.  However, Mehni reuses Toils for unloading inventory: if the pawn drops off in Deep Storage, the initAction is gone, but if the pawn then unloads in regular storage, DS logic assumes initAction will be there to handle placing items.

**Comment by lilwhitemouse** [comment]
Seems to be fixed.

**Comment by Mehni** [comment]
Hooray!
