### ISSUE TITLE
Screen occasionally flickers

### ISSUE THREAD

**Issue by The-Tarkol** [lilwhitemouse/RimWorld-LWM.DeepStorage#43]
Hello, after installing this mod I've been getting the occasional screen flicker. I turned on devmode and open+cleared the log, then as soon as it flickered I got an error message related to DeepStorage. Here's a direct screenshot of it;
![image](https://user-images.githubusercontent.com/24594751/63651473-9b4b6f00-c71a-11e9-9d80-cc98e7a990e8.png)

HugsLib also allowed me to make a link for the viewing of the full log;
https://gist.github.com/HugsLibRecordKeeper/7d583295c845e2541959d2c515d415ba

Let me know if there's anything I can do to help :)

**Comment by lilwhitemouse** [comment]
Does this happen in the most recent version?

**Comment by lilwhitemouse** [comment]
If this happens again, let me know
