### ISSUE TITLE
Wall refrigerators?

### ISSUE THREAD

**Issue by Taranchuk** [lilwhitemouse/RimWorld-LWM.DeepStorage#44]
I would like to use the Deep Refrigetaror, but it does not separate the rooms as the wall refrigerators from RimАridge do, unfortunately. So I would like to have a kitchen and dining room separately with deep refrigerators in between.

**Comment by Taranchuk** [comment]
So, I compared the files between the wall and non-wall refrigerators and found the following differences in the xml files. So here: 
```
		<passability>PassThroughOnly</passability>
		<fillPercent>0.4</fillPercent>
```
replaced by:
```
					<passability>Impassable</passability>
					<fillPercent>1</fillPercent>
```
and the following values ​​are added:
```
					<blockWind>true</blockWind>
					<coversFloor>true</coversFloor>
					<blockLight>true</blockLight>
					<canOverlapZones>false</canOverlapZones>
					<building>
						<canPlaceOverWall>true</canPlaceOverWall>
					</building>
					<drawPlaceWorkersWhileSelected>true</drawPlaceWorkersWhileSelected>
```
And it turns out the wall fridg . I’m not sure what exactly each value is responsible for, but I modified the Deep refrigerator myself and it now separates the rooms, as I wanted.

**Comment by lilwhitemouse** [comment]
The latest update should allow you to easily create a new deep wallfridge mod if you want:

<thingDef ParentName='LWM_DeepRimFridge'>
<blockWind>true</blockWind>
<coversFloor>true<...etc
<costList> - you could make it cost more?  Etc

But if you put that in a Defs folder in a new mod (the wiki has a good runthru (modding tutorials) on what you'd need), you would have a working wall-fridge mod that doesn't disappear when I update this.
