### ISSUE TITLE
Deep Storage Error occurs when creating brand new stockpile zones not near a DSU

### ISSUE THREAD

**Issue by joshuafcole** [lilwhitemouse/RimWorld-LWM.DeepStorage#46]
Not sure what could be going on here, unfortunately my mod list is quite long. I spent some time trying to remove as many of the other stockpile / hauling related mods from it as I could in the hopes that would help you see if I've got something unusual.

Steps to reproduce:
1. Create some DSU's
2. ...
3. ~Profit~ Attempt to create a few new stockpile zones. In some instances, Deep Storage will throw an exception, and only a small non-rectangular region of the stockpile will get created (as if there were already another zone or a wall in the way in the remaining tiles). 

A couple possibilities for step 2:
- Relocate a deep storage unit to a new location (have minify everything installed, if that's relevant).
- Attempt to use Haul Explicitly to store things in a DSU (this doesn't actually work, but potentially could have errored while I wasn't in dev mode to see it). ** This one seems likely, it's mentioned in the log **
- Unload a colonists inventory between a pair of DSU skips set to store silver while the pawn was carrying some ridiculous amount of silver. A few of the piles automatically fell into the skips.

Things I've tried:
- Removing as many other mods as I could which I thought could impact it.

Things I've not tried:
Removing Deep Storage, because I've got a few dozen DSU's now and really don't want to have to go around rebuilding and reconfiguring them all unless I run out of other options

Error log: https://pastebin.com/3TWsdW7g

Full mod list: (Mod Manager XML,  list of names in second half of file) https://pastebin.com/sPaQfAhK

Affected Save: https://drive.google.com/file/d/1nv2jwhPtywdjVDUZyZ4moSRHZe2nz5EN/view?usp=sharing

If you need anything else please @ping me!

I really appreciate how much your mod improves the game. :)

**Comment by lilwhitemouse** [comment]
Hey, sorry I missed this - I had misconfigured github and didn't get notifications.  I believe the root problem of this was solved a bit ago.  Please reopen / create a new issue if you see this again?  I should actually see it next time :)
