### ISSUE TITLE
Storage Containers Only Hold 2 Stacks

### ISSUE THREAD

**Issue by murderofphoenixes** [lilwhitemouse/RimWorld-LWM.DeepStorage#61]
Recently installed the mod. No issues with building the storage items, but all the storage containers only hold 2 stacks. It is as if the custom storage containers are treated as vanilla shelves.

Tried reinstalling the mod, shuffling its order in load, restarting my pc and working on different save files. Currently on version 1.0.2559, so perhaps version incompatibility? 

![Storage](https://user-images.githubusercontent.com/52829516/77130936-203c0400-6a30-11ea-9dcf-fd53a59f71b9.jpg)

**Comment by lilwhitemouse** [comment]
You have HugsLib running?  Can I get the HugsLib debug log?

**Comment by murderofphoenixes** [comment]
I was able to figure it out. Incompatibility with Fluffy's Stack Merger mod. Thank you for your time.
