### ISSUE TITLE
ModManager reports 1.1.0.9 is available

### ISSUE THREAD

**Issue by LoonyLadle** [lilwhitemouse/RimWorld-LWM.DeepStorage#78]
ModManager reports that a new versions, 1.1.0.9, is available. This seems to be because you are committing updates directly to the master branch. If you are going to support Mod Manager you can't do this.

**Comment by lilwhitemouse** [comment]
I simply forgot to create/upload that release!  Sorry about that.  If I can find a way to automagically create releases, I will!

1.1.0.10 has a major (if rare) bugfix, and that one is definitely available.
