### ISSUE TITLE
Could you include Lecris' uptdated version of Survival Tools to the weapons cabinet patch? 

### ISSUE THREAD

**Issue by jptrrs** [lilwhitemouse/RimWorld-LWM.DeepStorage#83]
Full name is [LC] Survival Tools, it can be found here: https://steamcommunity.com/sharedfiles/filedetails/?id=2057841936
I'd do a PR, but your patches aren't here. :-)

**Comment by lilwhitemouse** [comment]
https://github.com/lilwhitemouse/RimWorld-LWM.DeepStorage/tree/master/_Mod/LWM.DeepStorage/Patches
