### ISSUE TITLE
Can't scroll item list in the user defined storege settings page

### ISSUE THREAD

**Issue by kerrhyphen** [lilwhitemouse/RimWorld-LWM.DeepStorage#93]
Hi there, I'm trying to add some Apparel to the weapons cabinet, but since Apparel has options that always appear at the top of the section, regardless of any search terms, I can't see any actual items to allow...

Other categories aren't a problem since they don't have those special options at the top, but not being able to scroll the list is a hassle regardless. I'm running at 2560x1600 in 1x UI scaling. Not sure if any other mod could be interfering with your options page, but I'd be happy to post a modlist or log if that would help? 

See image:
![RimWorldWin64_2020-08-31_18-42-26](https://user-images.githubusercontent.com/7049369/91775721-bd8f8c80-ebb9-11ea-84fb-de638d993e15.png)

**Comment by lilwhitemouse** [comment]
I have no idea what's going on here - whatever modded ThingFilter you've got isn't properly drawing the scrollbars when it needs to - you should probably file a report with the other mod author and let them know they need to put in scrollbars for the entire thing if the Rect it has is too small.

Speaking of which, I'm doubling the size it has to display, and I hope that will address the problem!  If not, reopen this, and I'll see what else I can do :)
